import React, { useState } from 'react';
import { RiskLevel, SecurityReport } from '../types';
import {
  ShieldAlert,
  ShieldCheck,
  AlertTriangle,
  ExternalLink,
  Phone,
  Copy,
  Check,
  HelpCircle,
  FileWarning,
  Send,
  Building,
  Lock,
} from 'lucide-react';

interface EscalationMatrixProps {
  report: SecurityReport;
}

export const EscalationMatrix: React.FC<EscalationMatrixProps> = ({ report }) => {
  const [copiedTemplate, setCopiedTemplate] = useState(false);
  const [copiedIncident, setCopiedIncident] = useState(false);

  const riskLevel = report.risk_level;
  const isCriticalOrHigh = riskLevel === 'CRITICAL' || riskLevel === 'HIGH' || report.scam_threat_index >= 60;
  const isModerate = !isCriticalOrHigh && (riskLevel === 'MODERATE' || report.scam_threat_index >= 30);
  const isLow = !isCriticalOrHigh && !isModerate && (riskLevel === 'LOW' || (report.scam_threat_index > 0 && report.scam_threat_index < 30));
  const isUnknown = riskLevel === 'UNKNOWN' || report.scam_threat_index === 0;

  const verificationTemplateText = `Thank you for contacting me regarding this opportunity.

In compliance with standard corporate security protocols and personal identity protection guidelines, I require independent verification before sharing confidential information, scheduling video sessions, or proceeding further:

1. Corporate Landline & Email: Please provide your direct corporate telephone extension and message me directly from your official corporate domain email address (e.g., name@officialcompany.com).
2. Requisition Verification: Please supply the official Job Requisition ID and direct portal link on the verified corporate careers website.
3. Communications Policy: Please note that I do not conduct formal business interviews or exchange personal financial/banking details via Telegram, WhatsApp, or personal messaging channels.

Thank you for your cooperation in maintaining secure hiring and business practices.`;

  const incidentReportText = `--- CYBERSECURITY INCIDENT ESCALATION REPORT ---
Generated By: CyberSafe Fraud Shield
Date/Time: ${report.analyzed_at || new Date().toISOString()}
Classification: ${report.risk_level} (Threat Score: ${report.scam_threat_index}/100)
Category: ${report.category}

PRIMARY RED FLAGS:
${report.red_flags_detected.map((rf, idx) => `${idx + 1}. ${rf}`).join('\n')}

DECEPTIVE TACTICS IDENTIFIED:
${report.tactics_identified.map((t) => `- ${t}`).join('\n')}

FLAGGED CHANNELS / PAYMENT TARGETS:
${(report.suspicious_channels || []).join(', ') || 'N/A'}

EXECUTIVE SUMMARY:
${report.summary}

RECOMMENDED ACTION:
1. File complaint with FBI IC3 (ic3.gov) and Federal Trade Commission (reportfraud.ftc.gov).
2. Flag associated lookalike URLs at Google Safe Browsing.
3. Terminate all engagement immediately and alert enterprise security / HR teams.`;

  const handleCopyTemplate = () => {
    navigator.clipboard.writeText(verificationTemplateText);
    setCopiedTemplate(true);
    setTimeout(() => setCopiedTemplate(false), 2000);
  };

  const handleCopyIncident = () => {
    navigator.clipboard.writeText(incidentReportText);
    setCopiedIncident(true);
    setTimeout(() => setCopiedIncident(false), 2000);
  };

  return (
    <div
      id="safety-juridical-escalation-matrix"
      className="rounded-2xl border bg-white dark:bg-zinc-900 border-slate-200/90 dark:border-zinc-800 shadow-xs overflow-hidden transition-colors"
    >
      {/* Matrix Header */}
      <div className="px-5 py-3.5 border-b border-slate-100 dark:border-zinc-800 flex flex-wrap items-center justify-between gap-3 bg-slate-50/50 dark:bg-zinc-850/50">
        <div className="flex items-center gap-2.5">
          <div
            className={`w-8 h-8 rounded-xl flex items-center justify-center text-xs font-bold ${
              isCriticalOrHigh
                ? 'bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300'
                : isModerate
                ? 'bg-yellow-100 text-yellow-800 dark:bg-yellow-950 dark:text-yellow-300'
                : isLow
                ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300'
                : 'bg-slate-100 text-slate-700 dark:bg-zinc-800 dark:text-zinc-400'
            }`}
          >
            {isCriticalOrHigh ? '!' : isModerate ? '?' : isLow ? '✓' : '•'}
          </div>
          <div>
            <h3 className="text-xs uppercase tracking-wider text-slate-900 dark:text-zinc-100 font-bold flex items-center gap-2">
              Safety &amp; Escalation Guidance
            </h3>
            <p className="text-xs text-slate-500 dark:text-zinc-400">
              Recommended actions based on detected threat level
            </p>
          </div>
        </div>

        <span
          className={`text-xs px-2.5 py-1 rounded-full font-bold border ${
            isCriticalOrHigh
              ? 'bg-rose-50 text-rose-700 border-rose-200 dark:bg-rose-950/80 dark:text-rose-300 dark:border-rose-800'
              : isModerate
              ? 'bg-yellow-50 text-yellow-800 border-yellow-200 dark:bg-yellow-950/80 dark:text-yellow-300 dark:border-yellow-800'
              : isLow
              ? 'bg-emerald-50 text-emerald-800 border-emerald-200 dark:bg-emerald-950/80 dark:text-emerald-300 dark:border-emerald-800'
              : 'bg-slate-100 text-slate-700 border-slate-200 dark:bg-zinc-800 dark:text-zinc-400 dark:border-zinc-700'
          }`}
        >
          Risk Tier: {riskLevel}
        </span>
      </div>

      {/* Dynamic Content Body based on risk_level */}
      <div className="p-5">
        {/* 1. CRITICAL / HIGH RISK */}
        {isCriticalOrHigh && (
          <div className="space-y-4">
            <div className="p-3.5 rounded-xl bg-rose-50/70 dark:bg-rose-950/30 border border-rose-200 dark:border-rose-900/60 text-xs text-rose-900 dark:text-rose-200 flex items-start gap-3">
              <ShieldAlert className="w-5 h-5 text-rose-600 dark:text-rose-400 shrink-0 mt-0.5" />
              <div>
                <span className="font-bold text-rose-900 dark:text-rose-300 block mb-0.5 uppercase tracking-wide">
                  High Risk Scam / Fraud Warning
                </span>
                <p className="text-slate-700 dark:text-zinc-300 leading-relaxed">
                  This communication exhibits signs of financial extortion, advance-fee fraud, or brand impersonation.
                  Do not reply or click links. Report this incident through verified consumer protection and reporting portals below.
                </p>
              </div>
            </div>

            {/* Reporting Hotlinks Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-1">
              {/* FTC */}
              <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-zinc-950 border border-slate-200 dark:border-zinc-800 flex flex-col justify-between space-y-2.5">
                <div>
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-slate-900 dark:text-zinc-100 flex items-center gap-1.5">
                      <Building className="w-3.5 h-3.5 text-rose-600 dark:text-rose-400" />
                      FTC Fraud Registry
                    </span>
                    <span className="text-[10px] text-slate-400 dark:text-zinc-500">Consumer Protection</span>
                  </div>
                  <p className="text-xs text-slate-600 dark:text-zinc-400 mt-1">
                    Report consumer fraud, fake checks, and impersonator scams.
                  </p>
                </div>
                <div className="pt-2 border-t border-slate-200 dark:border-zinc-800/80 flex items-center justify-between gap-2 text-xs">
                  <a
                    href="https://reportfraud.ftc.gov"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-1 text-rose-600 dark:text-rose-400 hover:underline font-bold transition-colors"
                  >
                    <span>Report Online</span>
                    <ExternalLink className="w-3 h-3" />
                  </a>
                  <a
                    href="tel:18773824357"
                    className="inline-flex items-center gap-1 text-slate-500 dark:text-zinc-400 hover:text-slate-800 text-xs"
                    title="1-877-FTC-HELP"
                  >
                    <Phone className="w-3 h-3" />
                    <span>877-382-4357</span>
                  </a>
                </div>
              </div>

              {/* FBI IC3 */}
              <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-zinc-950 border border-slate-200 dark:border-zinc-800 flex flex-col justify-between space-y-2.5">
                <div>
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-slate-900 dark:text-zinc-100 flex items-center gap-1.5">
                      <Lock className="w-3.5 h-3.5 text-rose-600 dark:text-rose-400" />
                      FBI IC3
                    </span>
                    <span className="text-[10px] text-slate-400 dark:text-zinc-500">Cybercrime Unit</span>
                  </div>
                  <p className="text-xs text-slate-600 dark:text-zinc-400 mt-1">
                    Internet Crime Complaint Center for cyber scams, wire fraud, and phishing.
                  </p>
                </div>
                <div className="pt-2 border-t border-slate-200 dark:border-zinc-800/80 flex items-center justify-between gap-2 text-xs">
                  <a
                    href="https://www.ic3.gov"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-1 text-rose-600 dark:text-rose-400 hover:underline font-bold transition-colors"
                  >
                    <span>File IC3 Report</span>
                    <ExternalLink className="w-3 h-3" />
                  </a>
                  <span className="text-xs text-slate-400 dark:text-zinc-500">ic3.gov</span>
                </div>
              </div>

              {/* Google Safe Browsing */}
              <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-zinc-950 border border-slate-200 dark:border-zinc-800 flex flex-col justify-between space-y-2.5">
                <div>
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-slate-900 dark:text-zinc-100 flex items-center gap-1.5">
                      <FileWarning className="w-3.5 h-3.5 text-rose-600 dark:text-rose-400" />
                      Google Safe Browsing
                    </span>
                    <span className="text-[10px] text-slate-400 dark:text-zinc-500">Web Safety</span>
                  </div>
                  <p className="text-xs text-slate-600 dark:text-zinc-400 mt-1">
                    Submit malicious phishing URLs for browser warning protection.
                  </p>
                </div>
                <div className="pt-2 border-t border-slate-200 dark:border-zinc-800/80 flex items-center justify-between gap-2 text-xs">
                  <a
                    href="https://safebrowsing.google.com/safebrowsing/report_phish/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-1 text-rose-600 dark:text-rose-400 hover:underline font-bold transition-colors"
                  >
                    <span>Report URL</span>
                    <ExternalLink className="w-3 h-3" />
                  </a>
                  <span className="text-xs text-slate-400 dark:text-zinc-500">Global DNS</span>
                </div>
              </div>
            </div>

            {/* Quick Copy Incident Dossier */}
            <div className="pt-3 border-t border-slate-100 dark:border-zinc-800/80 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
              <span className="text-xs text-slate-600 dark:text-zinc-400">
                Need to escalate this to your internal security, legal, or IT team?
              </span>
              <button
                id="copy-escalation-dossier-btn"
                type="button"
                onClick={handleCopyIncident}
                className="inline-flex items-center justify-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-zinc-800 dark:hover:bg-zinc-750 text-slate-700 dark:text-zinc-200 border border-slate-200 dark:border-zinc-700 text-xs font-semibold transition-all shrink-0 shadow-2xs"
              >
                {copiedIncident ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-600" />
                    <span className="text-emerald-700 dark:text-emerald-400">Report Copied</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5 text-slate-500" />
                    <span>Copy Incident Summary</span>
                  </>
                )}
              </button>
            </div>
          </div>
        )}

        {/* 2. MODERATE RISK */}
        {isModerate && (
          <div className="space-y-4">
            <div className="p-3.5 rounded-xl bg-yellow-50/70 dark:bg-yellow-950/30 border border-yellow-200 dark:border-yellow-900/60 text-xs text-yellow-900 dark:text-yellow-200 flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-yellow-600 dark:text-yellow-400 shrink-0 mt-0.5" />
              <div>
                <span className="font-bold text-yellow-900 dark:text-yellow-300 block mb-0.5 uppercase tracking-wide">
                  Suspicious Elements Detected • Identity Challenge Advised
                </span>
                <p className="text-slate-700 dark:text-zinc-300 leading-relaxed">
                  The message lacks overt money requests but contains unverified claims or unexpected communication.
                  Do not provide sensitive data. Challenge the sender using the defensive verification template below.
                </p>
              </div>
            </div>

            {/* Interactive Template Box */}
            <div className="bg-slate-50 dark:bg-zinc-950 border border-slate-200 dark:border-zinc-800 rounded-xl p-3.5 relative">
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs text-yellow-800 dark:text-yellow-400 font-bold uppercase tracking-wider flex items-center gap-1.5">
                  <Send className="w-3 h-3 text-yellow-600" />
                  Recommended Safe Verification Response
                </span>
                <button
                  id="copy-verification-template-btn"
                  type="button"
                  onClick={handleCopyTemplate}
                  className="flex items-center gap-1 px-2.5 py-1 rounded-lg bg-white hover:bg-slate-100 dark:bg-zinc-800 dark:hover:bg-zinc-700 text-slate-700 dark:text-zinc-200 border border-slate-200 dark:border-zinc-700 text-xs font-medium transition-colors shadow-2xs"
                >
                  {copiedTemplate ? (
                    <>
                      <Check className="w-3 h-3 text-emerald-600" />
                      <span className="text-emerald-700">Copied</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3 h-3 text-slate-500" />
                      <span>Copy Template</span>
                    </>
                  )}
                </button>
              </div>
              <pre className="text-xs text-slate-700 dark:text-zinc-300 font-sans whitespace-pre-wrap leading-relaxed max-h-48 overflow-y-auto p-2 bg-white dark:bg-zinc-900 rounded-lg border border-slate-200 dark:border-zinc-800">
                {verificationTemplateText}
              </pre>
            </div>
          </div>
        )}

        {/* 3. LOW RISK */}
        {isLow && (
          <div className="p-4 rounded-xl bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800 text-emerald-900 dark:text-emerald-100 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div className="flex items-center gap-3.5">
              <div className="w-10 h-10 rounded-xl bg-emerald-100 dark:bg-emerald-900 flex items-center justify-center text-emerald-700 dark:text-emerald-300 shrink-0">
                <ShieldCheck className="w-6 h-6" />
              </div>
              <div>
                <span className="text-xs uppercase tracking-wider font-bold text-emerald-800 dark:text-emerald-300 block">
                  Authenticity Verification Passed
                </span>
                <p className="text-xs text-slate-600 dark:text-emerald-200/90 mt-0.5 leading-relaxed">
                  No advance fee demands, suspicious payment redirections, or unaligned sender domains detected.
                </p>
              </div>
            </div>
            <div className="px-3 py-1.5 rounded-xl bg-emerald-100 dark:bg-emerald-900/60 border border-emerald-300 dark:border-emerald-700 text-emerald-800 dark:text-emerald-200 text-xs font-bold shrink-0 text-center">
              Clear to Proceed
            </div>
          </div>
        )}

        {/* 4. UNKNOWN */}
        {isUnknown && (
          <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-zinc-800/60 border border-slate-200 dark:border-zinc-700 text-xs text-slate-600 dark:text-zinc-300 flex items-center gap-3">
            <HelpCircle className="w-5 h-5 text-slate-400 shrink-0" />
            <div>
              <span className="font-bold text-slate-800 dark:text-zinc-200 block mb-0.5">
                Inconclusive Input • No Escalation Required
              </span>
              <p className="text-slate-500 dark:text-zinc-400 leading-relaxed">
                The content provided did not contain enough structured text to detect threats.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
